apiVersion: apps/v1
kind: Deployment
metadata:
  name: happy-dog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: happy-dog
  template:
    metadata:
      labels:
        app: happy-dog
    spec:
      containers:
        - name: happy-dog-app
          image: gcr.io/amplified-brook-419416/happy-dog-project:2024.0426.135039
          ports:
            - containerPort: 8080
